config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|sr|sq/  do
    post 'measurements/search'
    get 'measurements/search_all', action: :search_all, controller: :measurements
    post 'measurements/search_all', action: :search_all, controller: :measurements

    resources :stories
    resources :measurements do
      get :by_location, on: :collection
    end
    resources :initiatives, only: :index
    resources :measurements_categories
    resources :about, only: [:index]
    resources :actors, only: [:show]
    resources :resources, only: [:index]
    resources :covid19, only: [:index]

    post "/contact" => "home#contact"
    get "/start" => "home#start"
    get "/recommendations" => "home#recommendations"
    get "/contact" => "home#contact"
    root to: "home#index"
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  resources :events do
    get 'events_json', on: :collection
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_calendar.html.erb
<%= stylesheet_link_tag '/css/monthly.css' %>
<h1 class="text-center mb-5"><%= t('.title')%></h1>
<div style="width:100%; display:inline-block; font-size: 11px;">
  <div class="monthly" id="mycalendar"></div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('#mycalendar').monthly({
      mode: 'event',
      //jsonUrl: 'events.json',
      //dataType: 'json'
      xmlUrl: 'events.xml'
    });
  });
</script>

app/views/shared/_change_locale.html.erb
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= t('language_name') %>
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown" data-turbolinks="false">
    <%= link_to t('language_name', locale: :en), request.params.merge(locale: :en), class: 'dropdown-item' %>
    <%= link_to t('language_name', locale: :sq), request.params.merge(locale: :sq), class: 'dropdown-item' %>
    <%= link_to t('language_name', locale: :sr), request.params.merge(locale: :sr), class: 'dropdown-item'  %>
  </div>
</li>

app/views/shared/_contact.html.erb
<div class="container">
   <div class="row">
     <div class="col-1 col-md-1"></div>
      <div class="col-10 col-md-10">
         <h1 class="pt-5 pb-3 align-center"><%= t('.title')%></h1>
         <%= form_with url: contact_path, method: :post, id: :custom_id, class: :custom_class  do |form| %>
            <div class="row">
               <div class="col">
                  <label for="nameInput"><%= t('.name')%></label>
                  <!-- <input type="text" class="form-control  hvr-grow" id="nameInput" placeholder="<%= t('.name')%>"> -->
                  <%= form.text_field :name, class: 'form-control  hvr-grow', placeholder: t('.name'), id: "nameInput"  %>
               </div>
               <div class="col">
                  <label for="emailInput"><%= t('.email')%></label>
                  <!-- <input type="text" class="form-control  hvr-grow" id="emailInput" placeholder="<%= t('.email')%>"> -->
                  <%= form.text_field :email, class: 'form-control  hvr-grow', placeholder: t('.email'), id: "emailInput"  %>
               </div>
            </div>
            <div class="row pt-3">
              <div class="col">
                <label for="emailInput"><%= t('.organization')%></label>
                <!-- <input type="text" class="form-control  hvr-grow" id="organizationInput" placeholder="<%= t('.organization')%>"> -->
                <%= form.text_field :organization, class: 'form-control  hvr-grow', placeholder: t('.organization'), id: "organizationInput"  %>
              </div>
            </div>
           <div class="form-group pt-3">
              <label for="contributionSelection"><%= t('.contribute')%></label>
              <select id="contributionSelection" class="custom-select hvr-grow">
                 <option><%= t('.tellus')%></option>
                 <option><%= t('.action')%></option>
                 <option><%= t('.report')%></option>
                 <option><%= t('.donate')%></option>
              </select>
           </div>
            <div class="row category-list-contact pb-3">
               <div class="col">
                  <label for="categorySelection"><%= t('.category')%></label>
                  <div><%= form.collection_select(:category, MeasurementCategory.all, :name, :name, {:selected => cookies[:last_seen_category]}, {class: "custom-select", id: "categorySelection"} ) %></div>
               </div>
               <div class="col">
                  <label for="hashtags"><%= t('.subject')%></label><br>
                  <select class="custom-select pl-0 pr-5" id="hashtags" name="hashtags[]" multiple>
                    <option value="central_govt"><%=t('.hashtag.central_govt')%></option>
                    <option value="local_govt"><%=t('.hashtag.local_govt')%></option>
                    <option value="cso"><%=t('.hashtag.cso')%></option>
                    <option value="media"><%=t('.hashtag.media')%></option>
                    <option value="international_organizations"><%=t('.hashtag.international_organizations')%></option>
                    <option value="gender"><%=t('.hashtag.gender')%></option>
                    <option value="education"><%=t('.hashtag.education')%></option>
                    <option value="religion"><%=t('.hashtag.religion')%></option>
                    <option value="justice"><%=t('.hashtag.justice')%></option>
                    <option value="youth"><%=t('.hashtag.youth')%></option>
                    <option value="language"><%=t('.hashtag.language')%></option>
                    <option value="transparency"><%=t('.hashtag.transparency')%></option>
                    <option value="culture"><%=t('.hashtag.culture')%></option>
                    <option value="economy"><%=t('.hashtag.economy')%></option>
                    <option value="environment"><%=t('.hashtag.environment')%></option>
                  </select>
               </div>
            </div>
            <div class="form-group">
               <label for="messageInput"><%= t('.message')%></label>
               <!-- <textarea class="form-control  hvr-grow" id="messageInput" rows="3"></textarea> -->
               <%= text_area_tag(:message, "",{ size: "24x3", class: "form-control hvr-grow"})%>
            </div>
            <!-- <button type="button" class="btn btn-primary btn-lg hvr-grow"><%= t('.submit')%></button> -->
          <div class="pb-3"><%= recaptcha_tags %></div>
           <%= form.submit t('.submit'), :class=> 'btn btn-primary btn-lg hvr-grow', :remote => true %>
         <% end %>
      </div>
     <div class="col-1 col-md-1"></div>
   </div>
</div>


<script type="text/javascript">
$(document).ready(function() {
   $('#hashtags').multiselect({
      nonSelectedText: I18n.t("shared.contact.select_hashtags")
   });
});
</script>

app/views/shared/_contribute_all.html.erb
<div class="container pt-5 pb-2">
   <div class="row">
      <div class="col-12 col-md-6">
        <h1 class="text-center mb-5"><%= t('home.contribute_all.latest_tweets') %></h1>
        <a class="twitter-timeline" data-height="450" href="https://twitter.com/trustbuildingks/lists/kosovo-trust-building?ref_src=twsrc%5Etfw">A Twitter List by trustbuildingks</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>      </div>
      <div class="col-12 col-md-6">
        <%= render 'shared/calendar' %>
      </div>
   </div>
</div>

app/views/shared/_counters.html.erb
<div id="counters" class="container">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-3 pt-5 hvr-grow text-center">
      <a style="color: #212B36 !important;" href="/<%= I18n.locale %>/recommendations">
        <h3 class="mb-5"><%= t('home.counters.recommendations') %></h3>
        <div id="recommendationcircle">
          <div class="number" style="font-weight: normal;"><span id="count"><%= @recommendations_count %></span></div>
        </div>
      </a>
    </div>
    <div class="col-12 col-md-6 col-lg-3 pt-5 hvr-grow text-center">
      <a style="color: #212B36 !important;" href="/<%= I18n.locale %>/resources">
        <h3 class="mb-5"><%= t('home.counters.initiatives') %></h3>
        <div id="initiativecircle">
          <div class="number" style="font-weight: normal;"><span id="count1"><%= @initiatives_count %></span></div>
        </div>
        </a>
    </div>
    <div class="col-12 col-md-6 col-lg-3 pt-5 hvr-grow text-center">
      <a style="color: #212B36 !important;" href="/<%= I18n.locale %>/resources">
        <h3 class="mb-5"><%= t('home.counters.actors') %></h3>
        <div id="actorcircle">
          <div class="number" style="font-weight: normal;"><span id="count2"><%= @actors_count %></span></div>
        </div>
      </a>
    </div>
    <div class="col-12 col-md-6 col-lg-3 pt-5 hvr-grow text-center">
      <a style="color: #212B36 !important;" href="/<%= I18n.locale %>/stories?category_id=4">
        <h3 class="mb-5"><%= t('home.counters.champions') %></h3>
        <div id="championcircle">
          <div class="number" style="font-weight: normal;"><span id="count3"><%= @champions_count ||= 1 %></span></div>
        </div>
      </a>
    </div>
  </div>
</div>
<script type="text/javascript">
  window.addEventListener('popstate', () => {
    location.reload();
  }, false);
</script>

<script type="text/javascript">
  // progressbar.js@1.0.0 version is used
  // Docs: http://progressbarjs.readthedocs.org/en/1.0.0/
  var fired = 0;
  $(document).on('turbolinks:load', function() {
    x = document.getElementById("count");
    x1 = document.getElementById("count1");
    x2 = document.getElementById("count2");
    x3 = document.getElementById("count3");
    x.style.display = "none";
    x1.style.display = "none";
    x2.style.display = "none";
    x3.style.display = "none";
  });

  $(window).scroll(function() {
    var hT = $('#counters').offset().top,
      hH = $('#counters').outerHeight(),
      wH = $(window).height(),
      wS = $(this).scrollTop();

    if ((wS > (hT+hH-wH) && (hT > wS) && (wS+wH > hT+hH) && fired == 0) || ($(window).width() < 993) && fired == 0) {
      x.style.display = "block";
      x1.style.display = "block";
      x2.style.display = "block";
      x3.style.display = "block";
      var bar = new ProgressBar.Circle(recommendationcircle, {
        color: '#FFEA82',
        trailColor: '#eee',
        trailWidth: 1,
        duration: 2000,
        easing: 'bounce',
        strokeWidth: 6,
        from: {color: '#FFEA82', a:0},
        to: {color: '#FE466C', a:1},
        // Set default step function for all animate calls
        step: function(state, circle) {
          circle.path.setAttribute('stroke', state.color);
        }
      });

      bar.animate(1.0);

      var bar1 = new ProgressBar.Circle(initiativecircle, {
        color: '#FFEA82',
        trailColor: '#eee',
        trailWidth: 1,
        duration: 2500,
        easing: 'bounce',
        strokeWidth: 6,
        from: {color: '#FFEA82', a:0},
        to: {color: '#866AFB', a:1},
        // Set default step function for all animate calls
        step: function(state, circle) {
          circle.path.setAttribute('stroke', state.color);
        }
      });

      bar1.animate(1.0);

      var bar2 = new ProgressBar.Circle(actorcircle, {
        color: '#FFEA82',
        trailColor: '#eee',
        trailWidth: 1,
        duration: 3000,
        easing: 'bounce',
        strokeWidth: 6,
        from: {color: '#FFEA82', a:0},
        to: {color: '#F6CD00', a:1},
        // Set default step function for all animate calls
        step: function(state, circle) {
          circle.path.setAttribute('stroke', state.color);
        }
      });

      bar2.animate(1.0);

      var bar3 = new ProgressBar.Circle(championcircle, {
        color: '#FFEA82',
        trailColor: '#eee',
        trailWidth: 1,
        duration: 3500,
        easing: 'bounce',
        strokeWidth: 6,
        from: {color: '#FFEA82', a:0},
        to: {color: '#06CBAD', a:1},
        // Set default step function for all animate calls
        step: function(state, circle) {
          circle.path.setAttribute('stroke', state.color);
        }
      });

      bar3.animate(1.0);

      $('#count').each(function () {
        $(this).prop('Counter',0).animate({
          Counter: $(this).text()
        }, {
          duration: 3000,
          easing: 'swing',
          step: function (now) {
            $(this).text(Math.ceil(now));
          }
        });
      });

      $('#count1').each(function () {
        $(this).prop('Counter',0).animate({
          Counter: $(this).text()
        }, {
          duration: 3000,
          easing: 'swing',
          step: function (now) {
            $(this).text(Math.ceil(now));
          }
        });
      });

      $('#count2').each(function () {
        $(this).prop('Counter',0).animate({
          Counter: $(this).text()
        }, {
          duration: 3000,
          easing: 'swing',
          step: function (now) {
            $(this).text(Math.ceil(now));
          }
        });
      });

      $('#count3').each(function () {
        $(this).prop('Counter',0).animate({
          Counter: $(this).text()
        }, {
          duration: 3000,
          easing: 'swing',
          step: function (now) {
            $(this).text(Math.ceil(now));
          }
        });
      });

      fired = 1;
    }
  });
</script>

app/views/shared/_fail.js.erb
$('#modal-window').find('.modal-body').html("");
$('#modal-window').find('.modal-body').append('<p><%= t('shared.fail.fail')%></p>');
$("#modal-window").modal('show');

app/views/shared/_header.html.erb
<div class="container">
   <nav class="navbar fixed-top navbar-expand-xl navbar-light bg-white">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="<%= t('.toggle_navigation')%>">
         <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand hvr-grow" href=<%=root_path %> >
         <img src="<%= asset_path('kosovo-logo-en.svg') %>" height="30" class="d-inline-block align-center" alt="<%= t('.logo_description')%>"><%= t('home.index.title') %>
      </a>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
         <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item hvr-underline-from-center"><%= link_to t('navbar.about'), about_index_path, class:'nav-link' %>
            </li>
            <li class="nav-item hvr-underline-from-center"><%= link_to t('navbar.start'), start_path, class:'nav-link' %>
            </li>
           <li class="nav-item hvr-underline-from-center"><%= link_to t('navbar.recommendations'), recommendations_path, class:'nav-link' %>
            <li class="nav-item hvr-underline-from-center"><%= link_to t('navbar.stories'), stories_path, class:'nav-link' %>
            </li>
            <li class="nav-item hvr-underline-from-center"><%= link_to t('navbar.gallery'), 'https://www.flickr.com/photos/185701275@N02/albums', class:'nav-link', target: 'blank' %></li>
           <li class="nav-item hvr-underline-from-center"><%= link_to t('navbar.resources'), "/#{I18n.locale}/resources", class:'nav-link' %></li>
            <li class="nav-item hvr-underline-from-center"><%= render 'shared/change_locale' %>
            </li>
         </ul>
         <%= render 'shared/meta_search' %>
      </div>
   </nav>
</div>

app/views/shared/_links.html.erb
<div class="text-center pb-5">
  <a href="http://radiokfor.com/" target="_blank" style="margin-right: 20px; margin-bottom: 20px; display: inline-block;"><img class="img-responsive" src="<%= asset_path('k4.png') %>" alt="" height="100"/></a>
  <a href="https://fjalor-recnik.com/" target="_blank" style="margin-right: 20px; margin-bottom: 20px; display: inline-block;"><img class="img-responsive" src="<%= asset_path('recnik-fjalor.png') %>" alt="" height="100"/></a>
  <a href="https://www.voc-up.com/" target="_blank" style="margin-right: 20px; margin-bottom: 20px; display: inline-block;"><img class="img-responsive" src="<%= asset_path('vocup.png') %>" alt="" height="100"/></a>
  <a href="http://unkt.org/2020/01/01/un75/" target="_blank"><img class="img-responsive" src="<%= asset_path('un75.jpg') %>" alt="" height="100"/></a>
</div>

app/views/shared/_meta_search.erb
<%= form_tag(measurements_search_all_path, :class => 'form-inline  my-2 my-lg-0 hvr-grow', method: :get) do %>
   <div class="input-group">
      <%= text_field_tag :search, params[:search], placeholder: t('navbar.search'), :class => 'form-control', 'aria-label': t('.search_for')%>
      <div class="input-group-append">
         <button class="btn btn-primary-search" type="submit" aria-label="<%=t('.start_search')%>">
         <i class="fa fa-search"></i>
         </button>
      </div>
   </div>
<% end %>

app/views/shared/_recommendations.html.erb
<div id="padding-cat" class="container mt-5">
  <h2 class="text-center"><%= t('.recommendations')%></h2>
  <div class="row">
    <% @measurements_categories.order('id ASC').each do |category| %>
      <div  class="col-12 col-md-6 col-lg-4 pt-5 hvr-grow text-center">
        <%= link_to measurements_path(:category_id => category.id) do %>
          <img src="<%= url_for(category.picture) if category.picture.attached? %>" class="img-fluid img-categories" width="60%" alt="<%= t('.stock_img')%> <%= category.id%>" aria-labelledby="category_header_<%= category.id%>">
          <h3 id="category_header_<%= category.id%>" class="pt-3 color-black"><%= category.name %></h3>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_results.html.erb
<% if initiatives.count == 0 %>
  <div class="container">
     <div id="notice"> <%= t('.not-found')%> </div>
  </div>
<% else %>
  <div class="container">
     <div id="notice"> 
     <%= t('.found', count: initiatives.uniq { |i| i[:title] }.count) %>
     </div>
     <%= render "shared/initiatives_table", initiatives: initiatives.uniq { |i| i[:title] } %>
  </div>
<% end %>


<script type="text/javascript">
  $(".btn-group .btn").click(function(){
    var inputValue = $(this).find("input").val();
    if(inputValue != 'all'){
      var target = $('table tr[data-status="' + inputValue + '"]');
      $("table tbody tr").not(target).hide();
      target.fadeIn();
    } else {
      $("table tbody tr").fadeIn();
    }
  });
</script>

app/views/shared/_results_all.erb
<div class="position-relative overflow-hidden pt-5">
   <div class="container">
      <div class="col-xl-12 col-lg-12 col-md-4 col-sm-12 pt-5 pb-5">
         <h1 class="font-weight-normal align-center pt-5">
            <i><%= @search_params %></i>
         </h1>
      </div>
   </div>
</div>
<% if ['LANGUAGE', 'YOUTH', 'HUMAN RIGHTS', 'GENDER EQUALITY'].include?(params[:search]) %>
  <div class="container">
    <div class="row">
      <div id="js-theme-id" visible="false" data-id=<%= params[:search] %>></div>
      <div id="js-for-theme" visible="false" data-id=true></div>
      <div class="col-md-12 text-center pt-5">
        <!--  Map with initiatives -->
        <div class="hvr-grow" id="map"> </div>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDyzOTCNZorbekjfuUuu6Sa3G3B2mJMTE0&callback=initMap&language=<%=I18n.locale%>" async defer></script>
      </div>
    </div>
  </div>
<% end %>

<% if results.count == 0 %>
  <div class="container pt-5">
     <div id="notice"> <%= t('.not-found')%> </div>
  </div>
<% else %>

  <% if @initiatives.count > 0 %>
    <div class="container">
      <%= render "shared/initiatives_table", initiatives: @initiatives %>
    </div>
  <% end %>

  <% if @stories.count > 0 %>
    <div class="container">
       <div class="col-sm-12">
          <h2 class="pt-5 pb-4 text-center"><%= t('.yourstories') %></h2>
          <div id="myBtnContainer" class="text-center pb-5">
             <button class="btn active montserrat size-16 hvr-underline-from-center" onclick="filterSelection('all')">
             <%= t('.all')%>
             </button>
             <% StoryCategory.all.each do |category| %>
               <button class="btn montserrat size-16 hvr-underline-from-center" onclick="filterSelection('<%= category.title.parameterize %>')">
               <%= category.title %>
               </button>
             <% end %>
          </div>
          <div class="masonry masonry-columns-3">
             <% @stories.each do |story| %>
             <div class="masonry-item hvr-grow js-initiatives filterDiv <%= story.story_category.title.parameterize %>">
                <% if story.picture.attached? %>
                <a href="<%= story_path(story) %>"><img src="<%= url_for(story.picture) %>" class="img-fluid center-block" alt="<%= story.picture.filename %>"></a>
                <% end %>
                <h3 class="post-title pt-3"><%= link_to story.title, story_path(story) %></h3>
                <p class="post-info"><%= story.created_at %></p>
                <p><%= story.summary %></p>
                <%= link_to t('.read-more'), story_path(story), class: 'read-more' %>
             </div>
             <% end %>
          </div>
       </div>
    </div>
  <% end %>

  <% if @measurements.count > 0 %>
  <div class="container">
     <h3 class="pb-4 text-center"><%= t('.recommendations')%></h3>
     <div class="card-columns">
        <% @measurements.each_with_index do |measurement, index| %>
        <div class="card">
           <div class="card-body">
              <h4 class="card-title hvr-grow"> <%= link_to ((index+1).to_s + '. ' +measurement.title), measurement_path(measurement) %></h4>
              <p class="card-text montserrat"><%= t('.initiatives', count: measurement.initiatives.count)%>
                 <% if measurement.has_fulfillment %>
              </p>
              <!-- PROGRESS BAR -->
              <div class="progress">
                 <div class="progress-bar" role="progressbar" style="width: <%= measurement.fulfillment %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" data-toggle="modal" data-target="#modal<%=measurement.id%>"><%= measurement.fulfillment.round %>%</div>
                 <div class="progress-bar color-grey" role="progressbar" style="width: <%= 10 - measurement.fulfillment %>;" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <!-- END PROGRESS BAR -->
              <div class="row">
                 <!-- PROGRESS AND READ MORE BUTTON -->
                 <div class="col-6 pt-2">
                    <p class="overview-tag hvr-underline-from-center" data-toggle="modal" data-target="#modal<%=measurement.id%>"><%= t('.progress')%></p>
                 </div>
                 <div class="col-6 pt-2">
                    <p class="overview-tag color-link-3 align-right" data-toggle="modal" data-target="#modal<%=measurement.id%>"><%= t('.read-more')%></p>
                 </div>
                 <!-- END PROGRESS AND READ MORE BUTTON -->
                 <!-- MODAL -->
                 <div class="modal fade" id="modal<%=measurement.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                       <div class="modal-content">
                          <div class="modal-header">
                             <h5 class="modal-title" id="exampleModalLabel"><%= measurement.title %></h5>
                             <button type="button" class="close" data-dismiss="modal" aria-label="<%=t('modal.close')%>">
                             <span aria-hidden="true">&times;</span>
                             </button>
                          </div>
                          <div class="modal-body">
                             <% if !measurement.description.nil? %>
                                 <h5><i class="fas fa-bookmark"></i> <%= t('.description')%> </h5> <%= markdown measurement.description %>
                             <% else %>
                                <%= t('.no-description')%>
                             <% end %>
                             <% if !measurement.summary.nil? %>
                            <h5><i class="fas fa-bookmark"></i> <%= t('.summary')%> <%= measurement.summary %></h5>
                             <% else %>
                             <h5><%= t('.no-summary')%></h5>
                             <% end %>
                          </div>

                          <div class="modal-footer">
                             <button type="button" class="btn btn-secondary hrv-grow" data-dismiss="modal"><%= t('.close')%></button>
                             <%= link_to t('.contribute'), about_index_path(anchor: 'how-can-i-contribute'), class: "btn btn-primary hvr-grow color-white"%>
                          </div>
                       </div>
                    </div>
                 </div>
                 <!-- END MODAL -->
              </div>
              <% elsif !measurement.description.nil? %>
              <p class="overview-tag" data-toggle="modal" data-target="#modal<%=measurement.id%>"><%= t('.read-more')%></p>
              <!-- MODAL -->
              <div class="modal fade" id="modal<%=measurement.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                 <div class="modal-dialog" role="document">
                    <div class="modal-content">
                       <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel"><%= measurement.title %></h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="<%=t('modal.close')%>">
                          <span aria-hidden="true">&times;</span>
                          </button>
                       </div>

                       <div class="modal-body">
                          <% if !measurement.description.nil? %>
                           <h5><i class="fas fa-bookmark"></i> <%= t('.description')%> <%= markdown measurement.description %> </h5>
                          <% else %>
                          <%= t('.no-description')%>
                          <% end %>
                          <% if !measurement.summary.nil? %>
                         <h5><i class="fas fa-bookmark"></i> <%= t('.summary')%> <%= measurement.summary %></h5>
                          <% else %>
                          <h5><%= t('.no-summary')%></h5>
                          <% end %>
                       </div>


                       <div class="modal-footer">
                          <button type="button" class="btn btn-secondary hvr-grow" data-dismiss="modal"><%=t('modal.close')%></button>
                          <%= link_to t('.contribute'), about_index_path(anchor: 'how-can-i-contribute'), class: "btn btn-primary color-white hvr-grow"%>
                       </div>
                    </div>
                 </div>
              </div>
              <!-- END MODAL -->
              <% end %>
              <p class="card-text montserrat"><small class="text-muted"><%= measurement.measurement_category.name %></small></p>
           </div>
        </div>
        <% end %>
     </div>
  </div>
  <% end %>
</div>


<% end %>

app/views/shared/_search_slide.html.erb
<div class="position-relative overflow-hidden pb-5">
   <div class="container">
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 pt-5 pb-5">
         <h1 class="display-4 font-weight-normal align-center pt-5"><%= t('.title')%></h1>
         <%= form_tag({controller: "measurements", action: "search"}, method: "post", remote: true) do %>
         <div class="row pt-3">
            <div class="col input-group">
               <%= collection_select(:query, :area, Area.all.sort_by{ |e| ActiveSupport::Inflector.transliterate(e.name.downcase) }, :id, :name, {include_blank: t('.where')}, {class: "custom-select", 'aria-label': t('.label.area')} ) %>
            </div>
            <div class="col input-group">
               <%= collection_select(:query, :category, MeasurementCategory.all.sort_by { |a| a.name  }, :id, :name, {include_blank: t('.category')}, {class: "custom-select", 'aria-label': t('.label.category')}  ) %>
            </div>
            <div class="col input-group">
               <%= collection_select(:query, :initiative_status, InitiativeStatus.all.sort_by { |a| a.name  }, :id, :status, {include_blank: t('.status')}, {class: "custom-select", 'aria-label': t('.label.initiative_status')}  ) %>
            </div>
            <div class="col input-group">
               <%= collection_select(:query, :actor, Actor.all.sort_by { |a| a.name  }, :id, :name, {include_blank: t('.actors')}, {class: "custom-select", 'aria-label': t('.label.actor')}  ) %>
            </div>
         </div>
         <div class="pt-4 align-center">  <%= submit_tag(t('.search_initiatives'), class: "btn btn-primary hvr-grow") %></div>
         <% end %>
      </div>
   </div>
</div>
<div>
   <div id="results"></div>
</div>

app/views/shared/_success.js.erb
$('#modal-window').find('.modal-body').html("");
$('#modal-window').find('.modal-body').append('<p><%= t('shared.success.thank-you')%></p>');
$("#modal-window").modal('show');
document.getElementById("custom_id").reset();