config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|sr|sq/  do
    post 'measurements/search'
    get 'measurements/search_all', action: :search_all, controller: :measurements
    post 'measurements/search_all', action: :search_all, controller: :measurements

    resources :stories
    resources :measurements do
      get :by_location, on: :collection
    end
    resources :initiatives, only: :index
    resources :measurements_categories
    resources :about, only: [:index]
    resources :actors, only: [:show]
    resources :resources, only: [:index]
    resources :covid19, only: [:index]

    post "/contact" => "home#contact"
    get "/start" => "home#start"
    get "/recommendations" => "home#recommendations"
    get "/contact" => "home#contact"
    root to: "home#index"
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  resources :events do
    get 'events_json', on: :collection
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @measurements_categories = MeasurementCategory.all
    @stories = Story.order('created_at DESC').limit(2)
    @highlighted = Story.where(highlight: true).order('created_at DESC').limit(3)
    @recommendations_count = Measurement.all.count
    @initiatives_count = Initiative.all.uniq { |i| i[:title] }.count
    @actors_count = Actor.all.count
    @champions_count = StoryCategory.where(id: 4)&.last&.stories&.count
  end

  def contact
    p contact_params
    if verify_recaptcha
      ApplicationMailer.with(params: contact_params).contact_email.deliver_later
      respond_to do |format|
        format.js { render :partial => 'shared/success.js.erb' }
      end
    else
      respond_to do |format|
        format.js { render :partial => 'shared/fail.js.erb' }
      end
    end
  end

  def start
  end

  def recommendations
    @measurements_categories = MeasurementCategory.all
  end

  private

    def contact_params
      params.permit(:category, :name, :email, :message, hashtags:[])
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_all_stories.html.erb
<div class="container pt-5">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-8">
      <h2 class="pb-5 text-center">
        <%= link_to stories_path do %>
          <%= t('all_stories.title') %>
        <% end %>
      </h2>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-4">
      <h2 class="pb-5 text-center">
        <%= link_to stories_path do %>
          <%= t('highlights.title') %>
        <% end %>
      </h2>
    </div>
  </div>
   <div class="row">
      <% @stories.each do |story| %>
       <div class="pb-5 col-sm-12 col-md-6 col-lg-4">
         <div class="card">
            <% if story.picture.attached? %>
            <a href="<%= story_path(story) %>"><img src="<%= url_for(story.picture) %>" class="card-img hvr-grow" alt="<%= story.picture.filename %>"></a>
            <% end %>
            <div class="card-body">
               <h3 class="card-title" id="story_heading_<%=story.id%>"><%= link_to story.title, story_path(story) %></h3>
               <%= story.actors.map{|actor| link_to actor.name, actor_path(actor), class: 'hvr-grow color-link'}.join(', ').html_safe %>
               <p class="card-text"><%= story.summary %></p>
               <% if story.members.exists? %>
                 <p class="card-text"> <%= t('all_stories.story_by') %> <%= story.members.map{|m| " " + m.name }.join(",") %></p>
               <% end %>
               <%= link_to t('all_stories.read_more'), story_path(story), class: 'btn btn-primary color-white btn-lg hvr-grow card-read-more', 'aria-labelledby': "story_heading_#{story.id}" %>
            </div>
         </div>
       </div>
     <% end %>
      <div class="pb-5 col-sm-12 col-md-6 col-lg-4">
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner story-card-carousel">
            <% @highlighted.each_with_index do |story, index| %>
              <div class="carousel-item item-story <% if index == 0  %>active<% end %>">
                <div class="card">
                  <% if story.picture.attached? %>
                    <a href="<%= story_path(story) %>"><img src="<%= url_for(story.picture) %>" class="card-img hvr-grow" alt="<%= story.picture.filename %>"></a>
                  <% end %>
                  <div class="card-body">
                    <h3 class="card-title" id="story_heading_<%=story.id%>"><%= link_to story.title, story_path(story) %></h3>
                    <%= story.actors.map{|actor| link_to actor.name, actor_path(actor), class: 'hvr-grow color-link'}.join(', ').html_safe %>
                    <p class="card-text"><%= story.summary %></p>
                    <% if story.members.exists? %>
                      <p class="card-text"> <%= t('all_stories.story_by') %> <%= story.members.map{|m| " " + m.name }.join(",") %></p>
                    <% end %>
                    <%= link_to t('all_stories.read_more'), story_path(story), class: 'btn btn-primary color-white btn-lg hvr-grow card-read-more', 'aria-labelledby': "story_heading_#{story.id}" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="stories-nav-prev" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="stories-nav-next" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
   </div>
</div>

app/views/home/_areas.html.erb
<div id="padding-cat" class="container">
<!--  <h2 class="text-center"><%#= t('.areas')%></h2>-->
  <div class="row">
    <div  class="col-12 col-md-6 col-lg-3 pt-5 hvr-grow text-center">
      <%= link_to measurements_search_all_path(search: 'LANGUAGE'), class: 'area-button' do %>
        <h3 class="pt-3" style="color: #FE466C">#<%= t('.language').upcase %></h3>
      <% end %>
    </div>
    <div  class="col-12 col-md-6 col-lg-3 pt-5 hvr-grow text-center">
      <%= link_to measurements_search_all_path(search: 'YOUTH'), class: 'area-button' do %>
        <h3 class="pt-3" style="color: #FE466C">#<%= t('.youth').upcase %></h3>
      <% end %>
    </div>
    <div  class="col-12 col-md-6 col-lg-3 pt-5 hvr-grow text-center">
      <%= link_to measurements_search_all_path(search: 'GENDER EQUALITY'), class: 'area-button' do %>
        <h3 class="pt-3" style="color: #FE466C">#<%= t('.gender').upcase %></h3>
      <% end %>
    </div>
    <div  class="col-12 col-md-6 col-lg-3 pt-5 hvr-grow text-center">
      <%= link_to measurements_search_all_path(search: 'HUMAN RIGHTS'), class: 'area-button' do %>
        <h3 class="pt-3" style="color: #FE466C">#<%= t('.human').upcase %></h3>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_home_carousel.html.erb
<div id="carousel" class="position-relative overflow-hidden pt-5 pb-5">
   <div class="">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
         
         <% carousel_slots = CarouselSlot.where(visible: true).order("ordering") %>
         <% fallback_to_default_carousel = carousel_slots.length == 0 %>
         <% show_carousel_controls = carousel_slots.length > 1 %>

         <ol class="carousel-indicators">

            <% if show_carousel_controls %>

               <!-- Aquí va un indicador por cada carousel slot que mostramos. -->
               <!-- Sólo aparecen si es que hay slots visibles -->
               <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>

               <% for i in 2..carousel_slots.length %>
                  <li data-target="#carouselExampleIndicators" data-slide-to="<%= i - 1 %>"></li>
               <% end %>
            <% end %>
         </ol>
         <div class="carousel-inner">            
            <% if fallback_to_default_carousel %>
               <!-- Aquí va el carousel slot por defecto si es que no hay ningún carousel slot guardado y
                 configurado como visible. -->
               <div class="carousel-item active">
                  <img class="d-block w-100" src="<%= asset_path('image.png') %>" alt="First slide">
                  <div class="carousel-caption no-bg">
                     <h1><%= t('.title_html')%></h1>
                  </div>
                  <div class="carousel-caption">
                     <h4 id="button-see" class="pb-4">
                        <%= link_to t('.see-more'), start_url, class: "btn btn-primary color-white btn-lg hvr-grow" %>
                     </h4>
                  </div>
               </div>
            <% else %>

               <% first_slot = carousel_slots.first %>

               <!-- Aquí va el primer carousel slot. Se hace por separado porque el html es distinto. -->
               <div class="carousel-item active">
                  <!-- Aquí va la imagen del carousel slot -->
                  <!-- Recordar poner un buen alt text. Probablemente parte de la base de datos. -->
                  <img class="d-block w-100" 
                     src="<%= get_resized_image_url first_slot.picture %>" 
                     alt="First slot's background">
                 <% unless first_slot.carousel_text == "don't display" %>
                  <div class="carousel-caption no-bg">
                     <!-- Aquí va el texto del slot-->
                     <h1><%= raw(first_slot.carousel_text) %></h1>
                  </div>
                  <% end %>
                  <div class="carousel-caption">
                     <h4 id="button-see" class="pb-4">
                        <!-- Aquí va el texto del link y el link -->
                        <%= link_to first_slot.link_text, make_any_url(first_slot.link), class: "btn btn-primary color-white btn-lg hvr-grow" %>
                     </h4>
                  </div>
               </div>

               <% carousel_slots.drop(1).each do |cs| %>
                  <!-- Aquí van los otros slots. Se hacen por separado porque el html es distinto. -->
                  <div class="carousel-item">
                     <img class="d-block w-100" src="<%= get_resized_image_url cs.picture %>" alt="">
                    <% unless cs.carousel_text == "don't display" %>
                     <div class="carousel-caption no-bg">
                        <h1><%= raw(cs.carousel_text) %></h1>
                     </div>
                    <% end %>
                     <div class="carousel-caption">
                        <h4 class="diplay-5 pb-4 text-center">
                           <%= link_to cs.link_text, make_any_url(cs.link), class: "btn btn-primary color-white btn-lg hvr-grow" %>
                        </h4>
                     </div>
                  </div>
               <% end %>
            <% end %>
         </div>
         <% if show_carousel_controls %>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </a>
         <% end %>
      </div>
   </div>
</div>

app/views/home/_measurement_categories.html.erb
<div id="padding-cat" class="container mt-5">
   <h2 class="text-center"><%= t('.recomendationsandinitiatives')%></h2>
   <div class="row">
      <% @measurements_categories.order('id ASC').each do |category| %>
      <div  class="col-12 col-md-6 col-lg-4 pt-5 hvr-grow text-center">
         <%= link_to measurements_path(:category_id => category.id) do %>
         <img src="<%= url_for(category.picture) if category.picture.attached? %>" class="img-fluid img-categories" width="60%" alt="<%= t('.stock_img')%> <%= category.id%>" aria-labelledby="category_header_<%= category.id%>">
         <h3 id="category_header_<%= category.id%>" class="pt-3 color-black"><%= category.name %></h3>
         <% end %>
      </div>
      <% end %>
   </div>
</div>

app/views/home/_start_hero.html.erb
<div class="position-relative overflow-hidden pt-5 pb-5">
   <div class="container pt-5">
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 pt-1 pb-5 align-left">
         <h1 class="font-weight-normal pt-5 align-center"><%= t('.subtitle')%></h1>
         <p class="font-weight-normal align-center"><%= t('.title')%></p>
      </div>
   </div>
</div>
<!-- //STORY INSIDE// -->
<div class="container pt-5 mt-5 pb-5">
<div class="col-sm-12">
   <div class="row">
      <div class="col-sm-12 col-md-6 blog-main">
         <div class="row pt-2">
            <p><%= t('.description') %></p>
           <div class="row well">
             <% MeasurementCategory.order('id ASC').each do |category| %>
               <div class="col-md-2 pt-2 text-right">
                 <img src="<%= url_for(category.picture) if category.picture.attached? %>" width="50px" alt="<%= category.picture.filename if category.picture.attached? %>">
               </div>
               <div class="col-md-10">
                 <div>
                   <%= link_to measurements_path(:category_id => category.id) do %>
                     <%= category.name %>
                   <% end %>
                 </div>
               </div>
             <% end %>
           </div>
         </div>
      </div>
      <div class="col-sm-12 col-md-6 blog-main">
         <div class="blog-post pt-2">
            <p><%= t('.description-more') %></p>
         </div>
      </div>
      <div class="col-sm-12 col-md-12 pt-5 align-center">
         <iframe width="100%" height="350" src="https://www.youtube-nocookie.com/embed/XaC4QpAYGcM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
   </div>
</div>
</div>

app/views/home/contact.html.erb
<div class="container pt-100">
  <%= render 'shared/contact' %>
</div>

app/views/home/contact.js.erb
$("#modal-window").modal();

app/views/home/index.html.erb
<%= render 'home_carousel' %>

<%= render 'areas' %>

<%= render 'shared/search_slide' %>

<%= render 'shared/counters' %>

<%= render 'all_stories' %>

<%= render 'measurement_categories' %>

<%= render 'shared/contribute_all' %>

<%= render 'shared/contact' %>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

app/views/home/recommendations.html.erb
<div class="container pt-100">
  <%= render 'shared/recommendations' %>
</div>

app/views/home/start.html.erb
<div class="container pt-5">
  <%= render 'start_hero' %>
  <%= render 'shared/contact' %>
</div>

<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>